# Generated by Django 6.0.8 on 2026-09-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0002_alter_journalmoderation_action_zonelivraison'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_column='reference', max_length=20, unique=True, verbose_name='reference')),
                ('adresse_nom', models.CharField(db_column='adresse_nom', max_length=150, verbose_name='destinataire')),
                ('adresse_telephone', models.CharField(db_column='adresse_telephone', max_length=20, verbose_name='telephone')),
                ('adresse_ville', models.CharField(db_column='adresse_ville', max_length=100, verbose_name='ville')),
                ('adresse_quartier', models.CharField(blank=True, db_column='adresse_quartier', max_length=120, verbose_name='quartier')),
                ('adresse_details', models.CharField(blank=True, db_column='adresse_details', max_length=255, verbose_name='precisions')),
                ('zone_nom', models.CharField(blank=True, db_column='zone_nom', max_length=100, verbose_name='zone de livraison')),
                ('frais_livraison', models.PositiveIntegerField(db_column='frais_livraison', default=0, verbose_name='frais de livraison (XAF)')),
                ('sous_total', models.PositiveIntegerField(db_column='sous_total', default=0, verbose_name='sous-total (XAF)')),
                ('total', models.PositiveIntegerField(db_column='total', default=0, verbose_name='total (XAF)')),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmee'), ('en_preparation', 'En preparation'), ('expediee', 'Expediee'), ('livree', 'Livree'), ('annulee', 'Annulee')], db_column='statut', default='en_attente_paiement', max_length=20, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='passee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('boutique', models.ForeignKey(db_column='boutique_id', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='boutiques.boutique', verbose_name='boutique')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'db_table': 'commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_column='designation', max_length=250, verbose_name='designation')),
                ('prix_unitaire', models.PositiveIntegerField(db_column='prix_unitaire', verbose_name='prix unitaire (XAF)')),
                ('quantite', models.PositiveIntegerField(db_column='quantite', verbose_name='quantite')),
                ('commande', models.ForeignKey(db_column='commande_id', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande', verbose_name='commande')),
                ('produit', models.ForeignKey(blank=True, db_column='produit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='produits.produit', verbose_name='produit')),
                ('variante', models.ForeignKey(blank=True, db_column='variante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='produits.varianteproduit', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
                'db_table': 'ligne_commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SuiviCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, db_column='ancien_statut', max_length=20, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, db_column='nouveau_statut', max_length=20, verbose_name='nouveau statut')),
                ('commentaire', models.TextField(blank=True, db_column='commentaire', verbose_name='commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='date', verbose_name='date')),
                ('auteur', models.ForeignKey(db_column='auteur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_commande', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('commande', models.ForeignKey(db_column='commande_id', on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='commandes.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'suivi de commande',
                'verbose_name_plural': 'suivis de commande',
                'db_table': 'suivi_commande',
                'ordering': ['-date'],
            },
        ),
    ]
