# Generated by Django 6.0.8 on 2026-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivicommande',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmee'), ('en_preparation', 'En preparation'), ('expediee', 'Expediee'), ('livree', 'Livree'), ('annulee', 'Annulee')], db_column='ancien_statut', max_length=20, verbose_name='ancien statut'),
        ),
        migrations.AlterField(
            model_name='suivicommande',
            name='nouveau_statut',
            field=models.CharField(blank=True, choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmee'), ('en_preparation', 'En preparation'), ('expediee', 'Expediee'), ('livree', 'Livree'), ('annulee', 'Annulee')], db_column='nouveau_statut', max_length=20, verbose_name='nouveau statut'),
        ),
    ]
