# Generated by Django 6.0.8 on 2026-09-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0002_alter_journalmoderation_action_zonelivraison'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=180, verbose_name='nom')),
                ('slug', models.SlugField(db_column='slug', max_length=200, verbose_name='slug')),
                ('description', models.TextField(db_column='description', verbose_name='description')),
                ('prix', models.PositiveIntegerField(db_column='prix', verbose_name='prix (XAF)')),
                ('stock', models.PositiveIntegerField(db_column='stock', default=0, verbose_name='stock (si pas de variantes)')),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='mis en vente par le vendeur')),
                ('masque_par_admin', models.BooleanField(db_column='masque_par_admin', default=False, verbose_name="masque par l'administrateur")),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
                ('boutique', models.ForeignKey(db_column='boutique_id', on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutiques.boutique', verbose_name='boutique')),
                ('categorie', models.ForeignKey(blank=True, db_column='categorie_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='categories.categorie', verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'db_table': 'produit',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_column='image', upload_to='produits/photos/', verbose_name='image')),
                ('principale', models.BooleanField(db_column='principale', default=False, verbose_name='photo principale')),
                ('ordre', models.PositiveSmallIntegerField(db_column='ordre', default=0, verbose_name='ordre')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='ajoutee le')),
                ('produit', models.ForeignKey(db_column='produit_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='produits.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'photo de produit',
                'verbose_name_plural': 'photos de produit',
                'db_table': 'photo_produit',
                'ordering': ['produit', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_column='libelle', help_text='Ex. : Rouge - M', max_length=100, verbose_name='libelle')),
                ('prix', models.PositiveIntegerField(blank=True, db_column='prix', help_text='Laisser vide pour utiliser le prix du produit.', null=True, verbose_name='prix (XAF)')),
                ('stock', models.PositiveIntegerField(db_column='stock', default=0, verbose_name='stock')),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('produit', models.ForeignKey(db_column='produit_id', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='produits.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'variante de produit',
                'verbose_name_plural': 'variantes de produit',
                'db_table': 'variante_produit',
                'ordering': ['produit', 'libelle'],
            },
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('boutique', 'slug'), name='unique_slug_par_boutique'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.UniqueConstraint(fields=('produit', 'libelle'), name='unique_libelle_par_produit'),
        ),
    ]
