# Generated by Django 6.0.8 on 2026-09-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_suivicommande_ancien_statut_and_more'),
        ('produits', '0002_produit_nombre_avis_produit_note_moyenne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('vente', 'Vente'), ('restock', 'Reapprovisionnement'), ('annulation', 'Annulation (stock retabli)')], db_column='type_mouvement', max_length=12, verbose_name='type')),
                ('quantite', models.PositiveIntegerField(db_column='quantite', verbose_name='quantite')),
                ('montant', models.PositiveIntegerField(blank=True, db_column='montant', null=True, verbose_name='montant (XAF)')),
                ('note', models.CharField(blank=True, db_column='note', max_length=200, verbose_name='note')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='date')),
                ('auteur', models.ForeignKey(blank=True, db_column='auteur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('commande', models.ForeignKey(blank=True, db_column='commande_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='commandes.commande', verbose_name='commande')),
                ('produit', models.ForeignKey(db_column='produit_id', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='produits.produit', verbose_name='produit')),
                ('variante', models.ForeignKey(blank=True, db_column='variante_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='produits.varianteproduit', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'db_table': 'mouvement_stock',
                'ordering': ['-date_creation'],
            },
        ),
    ]
