# Generated by Django 6.0.8 on 2026-09-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, db_column='slug', max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, db_column='description', verbose_name='description')),
                ('type', models.CharField(choices=[('boutique', 'Categorie de boutique'), ('produit', 'Categorie de produit')], db_column='type', default='produit', max_length=10, verbose_name='type')),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='active')),
                ('ordre', models.PositiveSmallIntegerField(db_column='ordre', default=0, verbose_name="ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='categories.categorie', verbose_name='categorie parente')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'db_table': 'categorie',
                'ordering': ['type', 'ordre', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('type', 'nom'), name='unique_nom_par_type_categorie')],
            },
        ),
    ]
