# Generated by Django 6.0.8 on 2026-09-12 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('administrateur', models.OneToOneField(db_column='administrateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_ia_admin', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
            ],
            options={
                'verbose_name': 'conversation IA (admin)',
                'verbose_name_plural': 'conversations IA (admin)',
                'db_table': 'conversation_ia_admin',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('utilisateur', 'Administrateur'), ('assistant', 'Assistant IA')], db_column='role', max_length=12, verbose_name='role')),
                ('contenu', models.TextField(db_column='contenu', verbose_name='contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='envoye le')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant_ia.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message IA (admin)',
                'verbose_name_plural': 'messages IA (admin)',
                'db_table': 'message_ia_admin',
                'ordering': ['date_creation'],
            },
        ),
    ]
