# Generated by Django 6.0.8 on 2026-09-09 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=80, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, db_column='slug', max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, db_column='description', verbose_name='description')),
                ('prix', models.PositiveIntegerField(db_column='prix', verbose_name='prix mensuel (XAF)')),
                ('duree_jours', models.PositiveIntegerField(db_column='duree_jours', default=30, verbose_name="duree d'une periode (jours)")),
                ('max_boutiques', models.PositiveIntegerField(blank=True, db_column='max_boutiques', help_text='Laisser vide pour un nombre illimite.', null=True, verbose_name='nombre max de boutiques')),
                ('max_roles', models.PositiveIntegerField(blank=True, db_column='max_roles', help_text='Laisser vide pour un nombre illimite.', null=True, verbose_name='nombre max de roles delegues')),
                ('delegation_roles', models.BooleanField(db_column='delegation_roles', default=True, verbose_name='delegation de roles autorisee')),
                ('ia_analyse_ventes', models.BooleanField(db_column='ia_analyse_ventes', default=False, verbose_name="IA d'analyse des ventes incluse")),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='propose a la souscription')),
                ('ordre', models.PositiveSmallIntegerField(db_column='ordre', default=0, verbose_name="ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'db_table': 'plan_abonnement',
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('actif', 'Actif'), ('expire', 'Expire'), ('annule', 'Annule')], db_column='statut', default='en_attente', max_length=12, verbose_name='statut')),
                ('montant', models.PositiveIntegerField(db_column='montant', default=0, verbose_name='montant paye (XAF)')),
                ('reference_paiement', models.CharField(blank=True, db_column='reference_paiement', max_length=100, verbose_name='reference de paiement')),
                ('date_debut', models.DateTimeField(blank=True, db_column='date_debut', null=True, verbose_name='debut')),
                ('date_fin', models.DateTimeField(blank=True, db_column='date_fin', null=True, verbose_name='echeance')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
                ('vendeur', models.ForeignKey(db_column='vendeur_id', on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL, verbose_name='vendeur')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'db_table': 'abonnement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
