# Generated by Django 6.0.8 on 2026-09-09 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=150, verbose_name='nom')),
                ('slug', models.SlugField(db_column='slug', max_length=170, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, db_column='logo', null=True, upload_to='boutiques/logos/', verbose_name='logo')),
                ('description', models.TextField(db_column='description', verbose_name='description')),
                ('telephone', models.CharField(db_column='telephone', max_length=20, verbose_name='telephone')),
                ('email', models.EmailField(db_column='email', max_length=254, verbose_name='e-mail')),
                ('adresse', models.CharField(blank=True, db_column='adresse', max_length=255, verbose_name='adresse')),
                ('ville', models.CharField(db_column='ville', max_length=100, verbose_name='ville')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('approuvee', 'Approuvee'), ('rejetee', 'Rejetee'), ('suspendue', 'Suspendue'), ('bannie', 'Bannie')], db_column='statut', default='brouillon', max_length=15, verbose_name='statut')),
                ('motif_rejet', models.TextField(blank=True, db_column='motif_rejet', verbose_name='motif du rejet / de la sanction')),
                ('date_soumission', models.DateTimeField(blank=True, db_column='date_soumission', null=True, verbose_name='soumise le')),
                ('date_decision', models.DateTimeField(blank=True, db_column='date_decision', null=True, verbose_name='decision le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('categorie', models.ForeignKey(blank=True, db_column='categorie_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boutiques', to='categories.categorie', verbose_name='categorie')),
                ('decide_par', models.ForeignKey(blank=True, db_column='decide_par_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques_moderees', to=settings.AUTH_USER_MODEL, verbose_name='decidee par')),
                ('proprietaire', models.ForeignKey(db_column='proprietaire_id', on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to=settings.AUTH_USER_MODEL, verbose_name='proprietaire')),
            ],
            options={
                'verbose_name': 'boutique',
                'verbose_name_plural': 'boutiques',
                'db_table': 'boutique',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JournalModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validation', 'Validation'), ('rejet', 'Rejet'), ('suspension', 'Suspension'), ('reactivation', 'Reactivation'), ('bannissement', 'Bannissement')], db_column='action', max_length=15, verbose_name='action')),
                ('motif', models.TextField(blank=True, db_column='motif', verbose_name='motif')),
                ('ancien_statut', models.CharField(blank=True, db_column='ancien_statut', max_length=15, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, db_column='nouveau_statut', max_length=15, verbose_name='nouveau statut')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='date', verbose_name='date')),
                ('administrateur', models.ForeignKey(db_column='administrateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_moderation', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
                ('boutique', models.ForeignKey(db_column='boutique_id', on_delete=django.db.models.deletion.CASCADE, related_name='evenements_moderation', to='boutiques.boutique', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'evenement de moderation',
                'verbose_name_plural': 'journal de moderation',
                'db_table': 'journal_moderation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoleBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_role', models.CharField(choices=[('gestionnaire', 'Gestionnaire'), ('vendeur', 'Vendeur'), ('caissier', 'Caissier')], db_column='type_role', max_length=15, verbose_name='type de role')),
                ('libelle', models.CharField(blank=True, db_column='libelle', help_text='Nom affiche, ex. : Vendeur 1.', max_length=50, verbose_name='libelle')),
                ('peut_gerer_produits', models.BooleanField(db_column='peut_gerer_produits', default=False, verbose_name='gerer les produits')),
                ('peut_gerer_stock', models.BooleanField(db_column='peut_gerer_stock', default=False, verbose_name='gerer le stock')),
                ('peut_gerer_commandes', models.BooleanField(db_column='peut_gerer_commandes', default=True, verbose_name='gerer les commandes')),
                ('peut_voir_statistiques', models.BooleanField(db_column='peut_voir_statistiques', default=False, verbose_name='voir les statistiques')),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
                ('boutique', models.ForeignKey(db_column='boutique_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='boutiques.boutique', verbose_name='boutique')),
                ('utilisateur', models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles_boutique', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'role de boutique',
                'verbose_name_plural': 'roles de boutique',
                'db_table': 'role_boutique',
                'ordering': ['boutique', 'type_role'],
                'constraints': [models.UniqueConstraint(fields=('boutique', 'utilisateur'), name='unique_role_par_utilisateur_boutique')],
            },
        ),
    ]
