# Generated by Django 6.0.8 on 2026-09-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmoderation',
            name='action',
            field=models.CharField(choices=[('soumission', 'Soumission'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('suspension', 'Suspension'), ('reactivation', 'Reactivation'), ('bannissement', 'Bannissement')], db_column='action', max_length=15, verbose_name='action'),
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=100, verbose_name='zone')),
                ('tarif', models.PositiveIntegerField(db_column='tarif', default=0, verbose_name='tarif de livraison (XAF)')),
                ('delai_estime', models.CharField(blank=True, db_column='delai_estime', help_text='Ex. : 24 a 48 h.', max_length=50, verbose_name='delai estime')),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('boutique', models.ForeignKey(db_column='boutique_id', on_delete=django.db.models.deletion.CASCADE, related_name='zones_livraison', to='boutiques.boutique', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'zone de livraison',
                'verbose_name_plural': 'zones de livraison',
                'db_table': 'zone_livraison',
                'ordering': ['boutique', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('boutique', 'nom'), name='unique_zone_par_boutique')],
            },
        ),
    ]
