# Generated by Django 6.0.8 on 2026-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_alter_journalmoderation_action_zonelivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='nombre_avis',
            field=models.PositiveIntegerField(db_column='nombre_avis', default=0, verbose_name="nombre d'avis"),
        ),
        migrations.AddField(
            model_name='boutique',
            name='note_moyenne',
            field=models.DecimalField(db_column='note_moyenne', decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne'),
        ),
    ]
