# Generated by Django 6.0.8 on 2026-09-09 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(db_column='nom_complet', max_length=150, verbose_name='nom complet (tel que sur la piece)')),
                ('date_naissance', models.DateField(blank=True, db_column='date_naissance', null=True, verbose_name='date de naissance')),
                ('type_piece', models.CharField(choices=[('cni', "Carte nationale d'identite"), ('passeport', 'Passeport'), ('permis', 'Permis de conduire')], db_column='type_piece', max_length=10, verbose_name='type de piece')),
                ('numero_piece', models.CharField(db_column='numero_piece', max_length=50, verbose_name='numero de la piece')),
                ('piece_recto', models.ImageField(db_column='piece_recto', upload_to='kyc/pieces/', verbose_name='piece - recto')),
                ('piece_verso', models.ImageField(blank=True, db_column='piece_verso', null=True, upload_to='kyc/pieces/', verbose_name='piece - verso')),
                ('selfie', models.ImageField(blank=True, db_column='selfie', null=True, upload_to='kyc/selfies/', verbose_name='photo du vendeur tenant la piece')),
                ('raison_sociale', models.CharField(blank=True, db_column='raison_sociale', max_length=150, verbose_name='raison sociale')),
                ('registre_commerce', models.FileField(blank=True, db_column='registre_commerce', null=True, upload_to='kyc/rccm/', verbose_name='registre de commerce (RCCM)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de verification'), ('valide', 'Valide'), ('rejete', 'Rejete')], db_column='statut', default='brouillon', max_length=12, verbose_name='statut')),
                ('motif_rejet', models.TextField(blank=True, db_column='motif_rejet', verbose_name='motif du rejet')),
                ('date_soumission', models.DateTimeField(blank=True, db_column='date_soumission', null=True, verbose_name='soumis le')),
                ('date_decision', models.DateTimeField(blank=True, db_column='date_decision', null=True, verbose_name='decision le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
                ('decide_par', models.ForeignKey(blank=True, db_column='decide_par_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_kyc_traites', to=settings.AUTH_USER_MODEL, verbose_name='verifie par')),
                ('vendeur', models.OneToOneField(db_column='vendeur_id', on_delete=django.db.models.deletion.CASCADE, related_name='dossier_kyc', to=settings.AUTH_USER_MODEL, verbose_name='vendeur')),
            ],
            options={
                'verbose_name': 'dossier KYC',
                'verbose_name_plural': 'dossiers KYC',
                'db_table': 'dossier_kyc',
                'ordering': ['-date_soumission', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JournalKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('soumission', 'Soumission'), ('validation', 'Validation'), ('rejet', 'Rejet')], db_column='action', max_length=12, verbose_name='action')),
                ('motif', models.TextField(blank=True, db_column='motif', verbose_name='motif')),
                ('ancien_statut', models.CharField(blank=True, db_column='ancien_statut', max_length=12, verbose_name='ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, db_column='nouveau_statut', max_length=12, verbose_name='nouveau statut')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='date', verbose_name='date')),
                ('administrateur', models.ForeignKey(db_column='administrateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_kyc', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
                ('dossier', models.ForeignKey(db_column='dossier_id', on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='kyc.dossierkyc', verbose_name='dossier')),
            ],
            options={
                'verbose_name': 'evenement KYC',
                'verbose_name_plural': 'journal KYC',
                'db_table': 'journal_kyc',
                'ordering': ['-date'],
            },
        ),
    ]
