# Generated by Django 6.0.8 on 2026-09-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0003_boutique_nombre_avis_boutique_note_moyenne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('boutique', models.OneToOneField(db_column='boutique_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_ia', to='boutiques.boutique', verbose_name='boutique')),
            ],
            options={
                'verbose_name': 'conversation IA',
                'verbose_name_plural': 'conversations IA',
                'db_table': 'conversation_ia',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('utilisateur', 'Vendeur'), ('assistant', 'Assistant IA')], db_column='role', max_length=12, verbose_name='role')),
                ('contenu', models.TextField(db_column='contenu', verbose_name='contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='envoye le')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vendeur_assistant.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message IA',
                'verbose_name_plural': 'messages IA',
                'db_table': 'message_ia',
                'ordering': ['date_creation'],
            },
        ),
    ]
