"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables d'environnement depuis .env (non versionne).
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z3wdu#pu!352w%3yr&$kumi8*#q^b*l*!l8$-0hsha_7tp!evz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Applications locales
    'account',

    # Applications du back-office administrateur (repertoire "admin/")
    'admin.categories',
    'admin.boutiques',
    'admin.abonnements',
    'admin.kyc',

    # Espace vendeur (repertoire "vendeur/")
    'vendeur.comptes',
    'vendeur.boutiques',
    'vendeur.roles',

    # Catalogue produits
    'admin.produits',
    'vendeur.produits',

    # Commandes (admin / acheteur / vendeur)
    'admin.commandes',
    'client.commandes',
    'vendeur.commandes',

    # Paiement (agregateur HR-Skills Pay)
    'admin.paiements',

    # Assistant IA d'analyse des ventes (reserve au forfait qui l'inclut)
    'vendeur.assistant',

    # Avis clients
    'admin.avis',
    'client.avis',

    # Espace client / acheteur (repertoire "client/")
    'client.comptes',
    'client.catalogue',
    'client.panier',
    'client.contact',
]

# Authentification de l'espace vendeur
LOGIN_URL = 'catalogue:connexion'
LOGIN_REDIRECT_URL = 'comptes_vendeur:tableau_de_bord'
LOGOUT_REDIRECT_URL = 'catalogue:landing'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'client.panier.context.panier',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Connexion a la base de donnees MySQL (marketplace_db).
# Les identifiants sont lus depuis les variables d'environnement afin de ne pas
# les versionner ; des valeurs par defaut de developpement sont fournies.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'marketplace_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Force le moteur InnoDB (transactions, cles etrangeres) et le mode
            # strict de MySQL, quelle que soit la configuration du serveur local.
            'init_command': (
                "SET default_storage_engine=INNODB, "
                "sql_mode='STRICT_TRANS_TABLES'"
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Aucune contrainte de robustesse sur les mots de passe : un utilisateur peut
# saisir n'importe quel mot de passe (court, courant, numerique...) sans que
# le formulaire d'inscription/changement de mot de passe ne le rejette.
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

# Marche mono-fuseau (Cameroun / zone CEMAC : UTC+1, sans changement d'heure).
# USE_TZ = False evite d'avoir a installer les tables de fuseaux horaires de
# MySQL (requises par date_hierarchy et les filtres __date quand USE_TZ = True).
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Fichiers televerses (logos de boutiques, etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modele utilisateur personnalise (application account).
AUTH_USER_MODEL = 'account.User'


# --- Agregateur de paiement HR-Skills Pay ---------------------------------
# Ne jamais committer les cles : les fournir via variables d'environnement.
HRSKILLS_BASE_URL = os.environ.get('HRSKILLS_BASE_URL', 'https://api.hrskills-pay.com')
HRSKILLS_KEY_A = os.environ.get('HRSKILLS_KEY_A', '')          # hrsk_pk_live_... / hrsk_pk_test_...
HRSKILLS_KEY_B = os.environ.get('HRSKILLS_KEY_B', '')          # hrsk_sk_... (jamais cote client)
# Sans cle : mode simulation local (contrat sandbox : montant pair -> SUCCESS).
HRSKILLS_MOCK = os.environ.get('HRSKILLS_MOCK', '') == '1' or not HRSKILLS_KEY_A
# Confirmation des paiements par polling (GET /v1/payments/:ref) : bouton
# "Verifier" cote utilisateur + commande de gestion "synchroniser_paiements".
HRSKILLS_POLL_TIMEOUT_MIN = int(os.environ.get('HRSKILLS_POLL_TIMEOUT_MIN', '20'))

# Operateurs Mobile Money disponibles au Cameroun.
OPERATEURS_MOBILE_MONEY = [
    ('orange', 'Orange Money'),
    ('mtn', 'MTN MoMo'),
    ('camtel', 'Camtel'),
]

# --- Assistant IA d'analyse des ventes (Groq, reserve au plan qui inclut
# "ia_analyse_ventes") -------------------------------------------------------
# Ne jamais committer la cle : fournie via variable d'environnement.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'openai/gpt-oss-120b')
# Sans cle : reponses simulees (mode demonstration, aucun appel reseau).
GROQ_MOCK = os.environ.get('GROQ_MOCK', '') == '1' or not GROQ_API_KEY
