# Generated by Django 6.0.8 on 2026-09-10 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(db_column='libelle', help_text='Ex. : Domicile, Bureau.', max_length=50, verbose_name='libelle')),
                ('nom_destinataire', models.CharField(db_column='nom_destinataire', max_length=150, verbose_name='nom du destinataire')),
                ('telephone', models.CharField(db_column='telephone', max_length=20, verbose_name='telephone')),
                ('ville', models.CharField(db_column='ville', max_length=100, verbose_name='ville')),
                ('quartier', models.CharField(blank=True, db_column='quartier', max_length=120, verbose_name='quartier')),
                ('details', models.CharField(blank=True, db_column='details', max_length=255, verbose_name='precisions (rue, reperes...)')),
                ('par_defaut', models.BooleanField(db_column='par_defaut', default=False, verbose_name='adresse par defaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='creee le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifiee le')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'adresse de livraison',
                'verbose_name_plural': 'adresses de livraison',
                'db_table': 'adresse_livraison',
                'ordering': ['-par_defaut', '-date_creation'],
            },
        ),
    ]
