# Generated by Django 6.0.8 on 2026-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=120, verbose_name='nom')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, verbose_name='e-mail')),
                ('telephone', models.CharField(blank=True, db_column='telephone', max_length=20, verbose_name='telephone')),
                ('message', models.TextField(db_column='message', verbose_name='message')),
                ('traite', models.BooleanField(db_column='traite', default=False, verbose_name='traite')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='recu le')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'db_table': 'message_contact',
                'ordering': ['-date_creation'],
            },
        ),
    ]
