# Generated by Django 6.0.8 on 2026-09-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0002_plans_par_defaut'),
        ('commandes', '0002_alter_suivicommande_ancien_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commande', 'Commande'), ('abonnement', 'Abonnement')], db_column='type', max_length=12, verbose_name='type')),
                ('montant', models.PositiveIntegerField(db_column='montant', verbose_name='montant (XAF)')),
                ('frais', models.PositiveIntegerField(db_column='frais', default=0, verbose_name='frais agregateur (XAF)')),
                ('montant_net', models.PositiveIntegerField(db_column='montant_net', default=0, verbose_name='montant net (XAF)')),
                ('devise', models.CharField(db_column='devise', default='XAF', max_length=3, verbose_name='devise')),
                ('operateur', models.CharField(db_column='operateur', max_length=20, verbose_name='operateur')),
                ('telephone', models.CharField(db_column='telephone', max_length=20, verbose_name='telephone payeur')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Reussi'), ('echoue', 'Echoue'), ('bloque', 'Bloque (revision AML)'), ('rembourse', 'Rembourse')], db_column='statut', default='en_attente', max_length=12, verbose_name='statut')),
                ('idempotency_key', models.CharField(db_column='idempotency_key', max_length=64, unique=True, verbose_name="cle d'idempotence")),
                ('reference_externe', models.CharField(blank=True, db_column='reference_externe', max_length=100, verbose_name='reference agregateur')),
                ('transaction_id', models.CharField(blank=True, db_column='transaction_id', max_length=64, verbose_name='transaction id agregateur')),
                ('reponse_brute', models.JSONField(blank=True, db_column='reponse_brute', default=dict, verbose_name='derniere reponse API')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
                ('date_confirmation', models.DateTimeField(blank=True, db_column='date_confirmation', null=True, verbose_name='confirme le')),
                ('abonnement', models.ForeignKey(blank=True, db_column='abonnement_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnements.abonnement', verbose_name='abonnement')),
                ('commande', models.ForeignKey(blank=True, db_column='commande_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'db_table': 'paiement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
