# Generated by Django 6.0.8 on 2026-09-12 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(db_column='titre', max_length=150, verbose_name='titre')),
                ('message', models.CharField(db_column='message', max_length=255, verbose_name='message')),
                ('lien', models.CharField(blank=True, db_column='lien', max_length=255, verbose_name='lien')),
                ('lu', models.BooleanField(db_column='lu', default=False, verbose_name='lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('destinataire', models.ForeignKey(db_column='destinataire_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
