# Generated by Django 6.0.8 on 2026-09-10 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0003_boutique_nombre_avis_boutique_note_moyenne'),
        ('commandes', '0002_alter_suivicommande_ancien_statut_and_more'),
        ('produits', '0002_produit_nombre_avis_produit_note_moyenne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(db_column='note', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('commentaire', models.TextField(blank=True, db_column='commentaire', verbose_name='commentaire')),
                ('statut', models.CharField(choices=[('publie', 'Publie'), ('masque', "Masque par l'administrateur")], db_column='statut', default='publie', max_length=10, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='date_creation', verbose_name='cree le')),
                ('date_modification', models.DateTimeField(auto_now=True, db_column='date_modification', verbose_name='modifie le')),
                ('auteur', models.ForeignKey(db_column='auteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('boutique', models.ForeignKey(blank=True, db_column='boutique_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='boutiques.boutique', verbose_name='boutique')),
                ('commande', models.ForeignKey(blank=True, db_column='commande_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='commandes.commande', verbose_name='commande liee')),
                ('produit', models.ForeignKey(blank=True, db_column='produit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='produits.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'db_table': 'avis',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('produit__isnull', False)), fields=('auteur', 'produit'), name='unique_avis_par_produit'), models.UniqueConstraint(condition=models.Q(('boutique__isnull', False)), fields=('auteur', 'boutique'), name='unique_avis_par_boutique'), models.CheckConstraint(condition=models.Q(models.Q(('boutique__isnull', True), ('produit__isnull', False)), models.Q(('boutique__isnull', False), ('produit__isnull', True)), _connector='OR'), name='avis_cible_unique')],
            },
        ),
    ]
